# Generated by Django 3.0.7 on 2021-10-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('eventdescription', models.TextField(blank=True, null=True)),
                ('detectingtime', models.DateTimeField()),
                ('fixingtime', models.DateTimeField(blank=True, null=True)),
                ('timeupdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('login', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('surname', models.CharField(max_length=127)),
                ('middlename', models.CharField(blank=True, max_length=127, null=True)),
                ('accesslist', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='buttonsevents',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='buttonsposts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='eventstypes',
            options={'managed': False},
        ),
    ]
