# Generated by Django 3.0.7 on 2021-10-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20211024_1429'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buttonsevents',
            table='buttonsevents',
        ),
        migrations.AlterModelTable(
            name='buttonsposts',
            table='buttonsposts',
        ),
        migrations.AlterModelTable(
            name='eventstypes',
            table='eventstypes',
        ),
    ]
