# Generated by Django 3.2.8 on 2021-11-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='usersS',
        ),
    ]
